project_id = "xeunjlpzvitnrepyzatg"

[functions.legal-chat]
verify_jwt = false

[functions.medical-chat]
verify_jwt = false

[functions.travel-assistant]
verify_jwt = false

[functions.travel-planner]
verify_jwt = false

[functions.community-chat]
verify_jwt = false

[functions.subject-chat-moderator]
verify_jwt = false

[functions.cyber-assistant]
verify_jwt = false
